version: "3.7"

services:
  mrbc:
    build: ./mrbc
    ports:
      - 4566:4566

  ide:
    build: ./ide
    ports:
      - 80:4567

  node-red:
    build: ./node-red
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data

volumes:
  node-red-data: