version: "3.7"

services:
  ide:
    build: ./ide
    ports:
      - 443:4567

  node-red:
    build: ./node-red
    ports:
      - 1880:1880
    volumes:
      - node-red-data:/data

  webpage:
    build: ./webpage
    ports:
      - 80:4567

volumes:
  node-red-data: